export const PATH_DASHBOARD = "/";
export const PATH_MONITOR = "/monitor";
export const PATH_ORDER = "/order";
export const PATH_AUTH_RESET = "/coordinator";
export const PATH_AUTH_REGISTER = "/schedule";
export const PATH_AUTH_LOGIN = "/customers";
export const PATH_ERROR = "/manager";
export const PATH_CUSTOMER = "/customers";
export const PATH_REPORTVEHICLE = "/report-vehicle"
export const PATH_REPORTORDER = "report-order"
export const PATH_REPORTDELIVERYORDER = "report-delivery-order"
export const PATH_REPORTDELIVERYVEHICLE = "report-delivery-vehicle"
export const PATH_REPORTBOT = "report-bot"
export const PATH_RULE = "report-rule"
export const PATH_INFOSTAFF = "/info-staff"
export const PATH_ACCOUNTSTAFF = "/account-staff"
export const PATH_PRODUCT = "/product"
export const PATH_PRODUCT_DETAIL = "/product-detail/:productId"
export const PATH_PRODUCT_TYPE = "/product-type"
export const PATH_PRODUCT_UNIT = "/unit"
export const PATH_ADMINISTRATIVE_AREA = "/admin-area"
export const PATH_INVENTORY = "/inventory"
export const PATH_TRANSPORT = "/transportation"
export const PATH_VEHICLE = "/vehicle"
export const PATH_SETTING_DASHBOARD = "/setting/dashboard"
export const PATH_SETTING_MONITOR = "setting/monitor"
export const PATH_SETTING_DELIVERYSCHEDULE = "setting/schedule"
export const PATH_SETTING_DELIVERYORDER = "setting/order"
export const PATH_SETTING_CUSTOMER = "setting/customer"
export const PATH_SETTING_ORDERTRACKING = "setting/order-tracking"
export const PATH_SETTING_DELIVERY = "setting/delivery"
export const PATH_SETTING_NOTIFICATION = "setting/notification"

// export const PATH_ERROR_404_MODERN = "/404-modern";
// export const PATH_ERROR_404_CLASSIC = "/404-classic";
// export const PATH_ERROR_504_MODERN = "/504-modern";
// export const PATH_ERROR_504_CLASSIC = "/504-classic";
// export const PATH_ORGANIZATION_INFORMATION = "/organization-information";
// export const PATH_ORGANIZATION_CONFIGURATION = "/organization-configuration";
// export const PATH_ROLES = "/roles";
// export const PATH_SUBSCRIPTION = "/subscription";
// export const PATH_SUBSCRIPTION_DETAILS =
//   "/subscription/subscription-detail/:id";
// export const PATH_SUBSCRIPTION_UPDATE = "/subscription/subcription-update";
// export const PATH_HISTORY_SYSTEM = "/history-system";
// export const PATH_HISTORY_PAYMENT = "/history-payment";
// export const PATH_INVOICE_LIST = "/invoice-list";
// export const PATH_INVOICE_DETAILS = "/invoice-details/:invoiceId";
// export const PATH_INVOICE_PRINT = "invoice-print/:invoiceId";
// export const PATH_APP_COMBO = "/app-combo";
// export const PATH_OPEN_API = "/openapi";
// export const PATH_USERS = "/users";
// export const PATH_USER_SUBSCRIPTION_DETAILS = "/users/subscription-detail";
// export const PATH_HELP = "/help";
// export const PATH_HELP_DETAIL = "/help/help-detail/:id";
// export const PATH_ACCOUNT_SETTING = "account-setting";

// export const PATH_403 = "/403";
