export enum QueryKeys {
  USER_INFO = 'user_info',
  USER = 'user',
  DEPARTMENT = 'department',
  ROLE = 'role',
  PERMISSION = 'permission',
  TRAM_MANAGEMENT = 'tram_management',
  BOAT_MANAGEMENT = 'boat_management',
  CATEGORY = 'category',
  USER_DETAIL = 'user_detail',
  STATION_MANAGEMENT = 'station',
  INCIDENT = 'INCIDENT',
  SCHEDULES = 'SCHEDULES',
  JOURNEY = 'JOURNEY',
  MAINTENANCE = 'MAINTENANCE',
  ASSIGNMENT = 'assignment',
  NOTIFICATION = 'notification',
  TRAM_MAP = 'tram_map',
  BOAT_MAP = 'boat_map',
}
